
<div class="content-header">
	<table cellspacing="0" class="grid-header">
		<tr>
			<td><h3 class="icon-head meinpaket"><?php echo __('Attribute Mappings'); ?></h3></td>
			<td class="a-right">
				<button onclick="addAttributeMapping()" class="scalable add"
					type="button" id="startButton">
					<span><?php echo $this->__('Add Attribute Mapping'); ?></span>
				</button>
			</td>
		</tr>
	</table>
</div>
todo
