<div class="content-header">
	<table cellspacing="0" class="grid-header">
		<tr>
			<td><h3 class="icon-head meinpaket">Importiere Bestellungen</h3></td>
			<td class="a-right">
				<button
					onclick="setLocation('<?php echo $this->getUrl('meinpaket/adminhtml_orderImport/index/') ?>')"
					class="scalable back" type="button">
					<span><?php echo $this->__('start again'); ?></span>
				</button>
				<button
					onclick="setLocation('<?php echo $this->getUrl('adminhtml/sales_order/index/') ?>')"
					class="scalable" type="button">
					<span><?php echo $this->__('view orders'); ?></span>
				</button>
			</td>
		</tr>
	</table>
</div>
<div class="dashboard-container meinpaket-content">
	 <?php echo $this->getChildHtml('steps'); ?>
	  <div class="cc">
		<!--  -->
	</div>
	<div class="meinpaket-description">
		<p>Bestellungen importiert</p>
		<button
			onclick="setLocation('<?php echo $this->getUrl('adminhtml/sales_order/index/') ?>')"
			class="scalable" type="button">
			<span><?php echo $this->__('view orders'); ?></span>
		</button>

	</div>

	<br />

</div>

