<?php
/**
 * Custom tab template
 */
?>

<?php $product = Mage::registry("current_product"); ?>

<div class="entry-edit">
	<div class="entry-edit-head">
		<h4 class="icon-head head-edit-form fieldset-legend">Suggestions</h4>
	</div>
	<div class="fieldset fieldset-wide" id="group_fields49">
		<div class="hor-scroll">
			<table cellspacing="0" class="form-list">
				<tbody>
					<tr>
						<td class="label"><label for="mp_name">Name</label></td>
						<td class="value"><?php echo $product->getName(); ?></td>
						<td class="value"><input id="mp_name" name="mp_name"
							type="checkbox" value="1" class="input-checkbox"></td>
					</tr>
					<tr>
						<td class="label"><label for="mp_ean">EAN</label></td>
						<td class="value"><?php echo Mage::helper('meinpaketcommon/product')->getEAN($product); ?></td>
						<td class="value"><input id="mp_ean" name="mp_ean" type="checkbox"
							value="1" class="input-checkbox" checked="checked"></td>
					</tr>
					<?php if(Mage::getSingleton('admin/session')->isAllowed('admin/meinpaket/matching')):?>
					<tr>
						<td colspan="3"><button onclick="loadSuggestions(); return false;"
								class="scalable btn-wysiwyg">Load suggestions</button></td>
					</tr>
					<?php endif;?>
				</tbody>
			</table>
		</div>
	</div>
</div>

<script type="text/javascript">
var mp_url = '<?php echo $this->getUrl('meinpaket/adminhtml_matching/index') ?>';
var mp_productId = <?php echo Mage::registry("current_product")->getId();?>;

function loadSuggestions() {
	var name = document.getElementById('mp_name');
	var ean = document.getElementById('mp_ean');

	if (name.checked || ean.checked) {
		new Ajax.Updater({
			success : 'mp_suggest_target'
		}, mp_url, {
			parameters : {
				id : mp_productId,
				name : name.checked ? 1 : 0,
				ean : ean.checked ? 1 : 0
			}
		});
	}
}
</script>

<div id="mp_suggest_target"></div>