<?php

/**
 * Common validation interface.
 * 
 * @category	Dhl
 * @package		Dhl_MeinPaket
 * @subpackage	Model_Validation
 * @version		$Id$
 */
interface Dhl_MeinPaketCommon_Model_Validation_ValidationInterface {
	const ERROR_UNDEFINED = 'undefinedError';
	const ERROR_REQUIRED_FIELD_IS_EMPTY = 'fieldIsEmpty';
	const ERROR_FIELD_IS_INVALID = 'invalidField';
	const ERROR_PRODUCT_NOT_EXISTS_IN_MEINPAKET = 'PRODUCT_NOT_FOUND';
	const ERROR_MEINPAKET_SERVER_ERROR = 'SERVER_ERROR';
	const ERROR_PRODUCT_NEGATIVE_STOCK = 'AVAILABILITY_NEGATIVE';
	const ERROR_NOT_AUTHORIZED = 'NOT_AUTHORIZED';
	const ERROR_INVALID_DATA = 'INVALID_DATA';
	const ERROR_INVALID_MODIFICATION = 'INVALID_MODIFICATION';
	const ERROR_NO_CATEGORIZATION = 'NO_CATEGORIZATION';
	const ERROR_PRODUCT_NOT_SELLABLE = 'PRODUCT_NOT_SELLABLE';
	const ERROR_MARKETPLACE_CATEGORY_NOT_FOUND = 'MARKETPLACE_CATEGORY_NOT_FOUND';
	const ERROR_SHOP_CATEGORY_NOT_FOUND = 'SHOP_CATEGORY_NOT_FOUND';
	const ERROR_MISSING_VALUE_FOR_ATTRIBUTE = 'MISSING_VALUE_FOR_ATTRIBUTE';
	const ERROR_VARIANT_GROUP_NOT_EXISTS = 'VARIANT_GROUP_NOT_FOUND';
}
