
<div class="content-header">
	<table cellspacing="0" class="grid-header">
		<tr>
			<td><h3 class="icon-head meinpaket">Export Products</h3></td>
			<td class="a-right">
				<button
					onclick="setLocation('<?php echo $this->getUrl('meinpaket/adminhtml_productExport/index/') ?>')"
					class="scalable back" type="button">
					<span><?php echo $this->__('start again'); ?></span>
				</button>
			</td>
		</tr>
	</table>
</div>
<div class="dashboard-container meinpaket-content">

	<div class="cc">
		<!--  -->
	</div>

	<p>Es gibt keine Produkte zum exportieren. Lernen Sie hier wie Sie neue
		Produkte zum exportieren auswählen:</p>
	<ul>
		<li>Ist Ihr Shop-Root korrekt gestetzt (Anchor und Shop-Root
			Eigenschaft)</li>
		<li>Wollen Sie alle Produkte unterhalb einer Kategorie exportieren?
			Wählöen Sie einfach "alle" aus</li>
		<li>Wollen Sie nur einzelne Produkte exportieren, so müssen Sie die
			Produkte als "zu meinPaket exportieren" markieren.</li>
	</ul>
	<br />

</div>

