
<div class="content-header">
	<table cellspacing="0" class="grid-header">
		<tr>
			<td><h3 class="icon-head meinpaket"><?php echo __('export products'); ?></h3></td>
			<td class="a-right">
				<button onclick="startProcessing()" class="scalable" type="button"
					id="startButton">
					<span><?php echo $this->__('export products'); ?></span>
				</button>
			</td>
		</tr>
	</table>
</div>
<div class="dashboard-container meinpaket-content">
	<ul class="meinpaket-steps">
		<li class="active nr1"><p><?php echo __('Selection'); ?></p></li>
		<li class="nr2"><p><?php echo __('Upload'); ?></p></li>
		<li class="nr3"><p><?php echo __('Result'); ?></p></li>
	</ul>
	<div class="cc">
		<!--  -->
	</div>

	<div id="meinpaket-description">
		<p><?php echo __('At this place you can choose which products you want to export and start the process.'); ?></p>
	</div>

	<div id="disabled-till-export" class="meinpaket-waitbox"
		style="display: none">
		<img src="/skin/adminhtml/default/default/meinpaket/images/loader.gif" /><br />
		<small><?php echo $this->__('please wait'); ?></small>
	</div>

	<form id="meinpaket_form" name="meinpaket_form" method="get"
		action="<?php echo $this->getUrl('meinpaket/adminhtml_productExport/export/') ?>">

		<fieldset>
			<label><?php echo $this->__('select products'); ?></label><select
				name="productselection"><option value="1"><?php echo $this->__('only marked products'); ?></option>
				<option value="2"><?php echo $this->__('all'); ?></option></select>
			<button onclick="startProcessing()" class="scalable" type="button"
				id="startButton">
				<span><?php echo $this->__('export products'); ?></span>
			</button>
			<!-- <button onclick="submitForm('<?php echo $this->getUrl('meinpaket/adminhtml_productExport/list/') ?>')" class="scalable" type="button"><span><?php echo $this->__('list products'); ?></span></button>  -->
		</fieldset>
	</form>
	<br />

</div>

