
<div class="content-header">
	<table cellspacing="0" class="grid-header">
		<tr>
			<td><h3 class="icon-head meinpaket">Export Products</h3></td>
			<td class="a-right">
				<button
					onclick="setLocation('<?php echo $this->getUrl('meinpaket/adminhtml_productExport/index/') ?>')"
					class="scalable" type="button">
					<span><?php echo $this->__('start'); ?></span>
				</button>
			</td>
		</tr>
	</table>
</div>
<div class="dashboard-container meinpaket-content">

	<div class="cc">
		<!--  -->
	</div>
	<div id="meinpaket-results" class="scrollablebox"> 
	<?php
	
	foreach ( $productCollection as $product ) {
		print_r ( $product->debug () );
		echo '<hr />';
	}
	
	?>
   </div>
</div>

