<?php if(!$this->getMappingExists()) : ?>
<script type="text/javascript">
MeinPaket.magentoAttributes = <?php echo $this->getAvailableMagentoAttributes(); ?>;
MeinPaket.meinpaketAttributes = <?php echo $this->getAvailableMeinPaketAttributes(); ?>;
MeinPaket.url = {};
MeinPaket.url.editAttributeValues = "<?php echo $this->getUrl('*/*/loadAttributeValues'); ?>";
</script>
<div class="entry-edit custom-options bundle"
	id="meinpaket_attributes_container">
	<div class="entry-edit-head">
		<h4><?php echo $this->__('Attributes') ?></h4>
		<div class="right"><?php echo $this->getAddButtonHtml() ?></div>
	</div>

	<div id="meinpaket_attribute" class="box">
		<div id="meinpaket_attribute_top"></div>
	</div>
</div>
<?php else : ?>
<div><?php echo $this->__('A mapping for the Magento attribute set already exists.'); ?></div>
<?php endif; ?>