<div
	id="attribute_mapping_container_<?php echo $this->getCurrentIndex(); ?>"
	class="option-box attribute-mapping-container">
	<table class="option-header" cellpadding="0" cellspacing="0">
		<thead>
			<tr>
				<th class="opt-type"><?php echo $this->__('Magento Attribute'); ?></th>
				<th class="opt-req"><?php echo $this->__('MeinPaket Attribute'); ?></th>
				<th>&nbsp;</th>
				<th>&nbsp;</th>
			</tr>
		</thead>
		<tbody id="attribute_table_<?php echo $this->getCurrentIndex(); ?>">
			<tr>
				<td><?php echo $this->getAttributeSetAttributesSelectElement()->toHtml(); ?></td>
				<td><?php echo $this->getVariantAttributesSelectElement()->toHtml(); ?></td>
				<td>
					<button type="button" value="" class="scalable add"
						onclick="MeinPaket.loadValueMapping(<?php echo $this->getCurrentIndex(); ?>);">
						<span><?php echo $this->__('Edit Value Mapping'); ?></span>
					</button>
				</td>
				<td>
					<button type="button" value="" class="scalable delete"
						onclick="MeinPaket.deleteAttributeMapping(<?php echo $this->getCurrentIndex(); ?>);">
						<span><?php echo $this->__('Delete Mapping'); ?></span>
					</button>
				</td>
			</tr>
			<tr id="values_row_<?php echo $this->getCurrentIndex(); ?>">
				<td colspan="4"></td>
			</tr>
		</tbody>
	</table>
	<div id="values_container_<?php echo $this->getCurrentIndex(); ?>"></div>
</div>