<?php
/* @var $block Dhl_MeinPaket_Block_Adminhtml_Attributemapping_Edit_Valuemapping */
$block = $this;
$mpValues = $block->getMeinpaketOptions ();
$mageValues = $block->getMagentoOptions ();
$mappingId = $block->getMappingIndex ();
?>
<?php if(sizeof($mpValues) > 0) : ?>
<tr>
	<th><?php echo Mage::helper('meinpaket')->__('Magento Value'); ?></th>
	<th><?php echo Mage::helper('meinpaket')->__('MeinPaket Value'); ?></th>
	<th>&nbsp;</th>
	<th>&nbsp;</th>
</tr>
<?php foreach($mageValues as $mageValue): ?>
		<?php
		$mpSelect = '<select id="attribute_value_id_' . $mageValue ['id'] . '" name="attribute_value_mapping[' . $mappingId . '][' . $mageValue ['id'] . ']">';
		$mpSelect .= '<option value="">' . Mage::helper ( 'meinpaket' )->__ ( 'not assigned' ) . '</option>';
		foreach ( $mpValues as $mpValue ) {
			$mpSelect .= '<option value="' . $mpValue ['id'] . '" ';
			if ($mpValue ['assigned'] !== null && $mpValue ['assigned'] == $mageValue ['id']) {
				// if($mageValue['name'] == $mpValue['name']) {
				$mpSelect .= 'selected="selected"';
			}
			$mpSelect .= '>' . $mpValue ['name'] . '</option>';
		}
		?>
<tr>
	<td><?php echo $mageValue['name']; ?></td>
	<td><?php echo $mpSelect; ?></td>
	<td>&nbsp;</td>
	<td>&nbsp;</td>
</tr>
<?php endforeach; ?>
<?php else : ?>
<tr>
	<td colspan="4">
			<?php echo $this->__('No mapable attribute values available for the selected MeinPaket attribute.'); ?><br /><?php echo $this->__('Magento attribute values will be used instead.'); ?>	
		</td>
</tr>
<?php endif; ?>