<?php if ($this->isPossibleOnepageCheckout()):?>
<button type="button"
	title="<?php echo $this->__('Proceed to Checkout') ?>"
	class="button btn-checkout<?php if ($this->isDisabled()):?> no-checkout<?php endif; ?>"
	<?php if ($this->isDisabled()):?> disabled="disabled" <?php endif; ?>
	onclick="window.location='<?php echo $this->getCheckoutUrl() ?>';">
	<span><span><?php echo $this->__('Proceed to Checkout') ?></span></span>
</button>
<?php if ( (bool)Mage::getStoreConfig('meinpaket/checkout/available') ) { ?>
<p style="margin-top: 10px;">
	<a
		href="<?php echo Mage::app()->getStore()->getUrl() ?>meinpaket/checkout/redirect">
		<img
		src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB) ?>skin/frontend/default/default/meinpaket/images/dhl_checkout_button.png"
		alt="POSTPAY" title="POSTPAY" />
	</a>
</p>
<?php } ?>
<?php endif?>