<?php
$checkoutIsPossible = false;

foreach ( Mage::getSingleton ( 'checkout/session' )->getQuote ()->getItemsCollection () as $item ) {
	$checkoutIsPossible = true;
}
?>
<?php if ($checkoutIsPossible) { ?>
  <?php if ( (bool)Mage::getStoreConfig('meinpaket/checkout/available') ) { ?>
<div class="block">
	<div class="block-content">
		<a
			href="<?php echo Mage::app()->getStore()->getUrl() ?>meinpaket/checkout/redirect"
			style="display: block; text-align: center; margin-bottom: 5px;"> <img
			src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB) ?>skin/frontend/default/default/meinpaket/images/dhl_checkout_button.png"
			alt="POSTPAY" title="POSTPAY" />
		</a>
	</div>
</div>
<?php } ?>
<?php } ?>
