<link rel="stylesheet" type="text/css"
	href="/skin/adminhtml/default/dhl_meinpaket/module.css" />
<div class="content-header">
	<table cellspacing="0" class="grid-header">
		<tr>
			<td><h3 class="icon-head meinpaket">Export Products</h3></td>
			<td class="a-right">
				<button
					onclick="setLocation('<?php echo $this->getUrl('meinpaket/adminhtml_productExport/export/') ?>')"
					class="scalable save" type="button">
					<span><?php echo $exportLabel; ?></span>
				</button>
			</td>
		</tr>
	</table>
</div>
<div class="dashboard-container">
	<form id="myform" name="myform" method="post"
		action="<?php echo $this->getUrl('web/adminhtml_myform/post/') ?>">

		<ul class="meinpaket-steps">
			<li class="active nr1"><p>Wählen Sie aus welche Produkte hochgeladen
					werden sollen</p></li>
			<li class="nr2"><p>Upload</p></li>
			<li class="nr3"><p>Results</p></li>
		</ul>

</div>

